### ISSUE TITLE
Offline Piholes sind jetzt Offlind

### ISSUE THREAD

**Issue by nicedevil007** [naimo84/node-red-contrib-pi-hole-remote#11]
Huhu, da bin ich mal wieder.

Gerade mal net im Halbschlaf gewesen wo ich über mein Dashboard gestolpert bin.

![image](https://user-images.githubusercontent.com/17103076/73294837-d5a7c380-4206-11ea-9a7a-48ae3792510d.png)

Kannst du da wieder nen "e" draus machen <3? Danke.

**Comment by naimo84** [comment]
Hey du,

Würde ich gerne, aber ich finde kein offlind im Code ....

Siehe hier: 
![image](https://user-images.githubusercontent.com/11535502/73334223-77153080-426c-11ea-9b1e-783d548ea1a1.png)

Ich kann höchstens nochmal eine Version mit dem selben Code hochladen.

**Comment by nicedevil007** [comment]
Ohje....

Habs gefunden, sry :)
Bei Disable wollte ich, dass "Disabled" da steht...
Tja... jetzt macht er halt beim letzten Zeichen nen D draus.... Fehler 88, Problem sitzt vor dem Bildschirm ;) Danke dennoch.

```
if (doit) {
    status[n] = m.status.slice(0,m.status.length-1);
    newstatus = status[n]+'d';
    context.set('status', status);
```
