### ISSUE TITLE
Falsche Disabletime?

### ISSUE THREAD

**Issue by nicedevil007** [naimo84/node-red-contrib-pi-hole-remote#4]
Hey naimo,

hab leider ein schwer zu debuggendes Problemchen festgestellt und kanns net immer reproduzieren :/

Gestern abend hab ich meinen Flow mit deiner Node überarbeitet (einmal wieder :D) und musste dann wieder das feststellen, was ich damals auf meinen vermeintlich defekten Raspberry geschoben hatte (ist net defekt).

Wenn ich mit deiner Node den Pihole ausschalte und einen Timer für 900 sec (15 Min eingestellt habe) macht er random manchmal irgendeine andere viel kürzere Zeit (gestern warens irgendwas über 8 Min). Ja ich habe den Browsercache gelöscht gehabt um es zu prüfen.

2. Problem:
Mein Pihole switcht auf 1 blocked Domain. Siehe Screen fresh refreshed mit STRG + F5 im Browser:

![grafik](https://user-images.githubusercontent.com/17103076/65975932-ae670280-e46f-11e9-9bc7-e7a583894673.png)

Oben zeigt er an "offline" aber dein Status bringt "enabled":

![grafik](https://user-images.githubusercontent.com/17103076/65975980-c0e13c00-e46f-11e9-8511-5b9ef656b8bf.png)

Kann es sein, dass du die Node so programmiert hast, dass sie bei 0 Domains Blocked den Status enabled ausgibt und nur bei 0 disabled? Kann man das nicht an den Pihole eigenen Status knüpfen oder ggf. die verbleibende Disabletime dafür hernehmen? (wenn die gleich 0 sekunden ist, dann status enabled?)

Oder liege ich komplett falsch und hier ist es ein reines pihole eigenes Problem?

**Comment by naimo84** [comment]
Hey nicedevil,

beides sind wohl leider reine pihole Probleme... Sorry.

Du kannst mal versuchen, die Pi-hole API direkt aufzurufen.

Disable für 900sec --> http://${config.url}/admin/api.php?$**disable=900**&auth=${config.auth}
Danach Statusabruf --> http://${config.url}/admin/api.php?$**summaryRaw**&auth=${config.auth}

Das sollte zum gleichen Ergebnis führen. Ich habe keinerlei Logik für enable/disable eingebaut.

**Comment by nicedevil007** [comment]
Könntest du ne Logik aber einbauen? So grundsätzlich?
Also dass er wenn naxch wie vor Offline angezeigt wird, dann auch "disable" raushaut anstatt "enable" nur weil da eine Domain auf der Blocklist ist?

**Comment by naimo84** [comment]
Theoretisch ja, aber es muss ja einen Grund geben, warum immer noch eine Domain auf der Blocklist ist 😉

 ich hab grad ne Viertelstunde rumprobiert, es kommt immer 0 bei disable raus. Was ich allerdings grad festgestellt habe... Auch bei mir stimmt die disable time nicht immer 100%. Allerdings hab ich grad alles über die Oberfläche getestet und nicht über meine node. Von daher tippe ich ernsthaft auf ein pihole Problem. Ich recherchiere mal weiter

**Comment by naimo84** [comment]
So ein ähnliches Problem ist bei den Jungs und Mädels von pihole wohl schon als Bug bekannt.. https://github.com/pi-hole/AdminLTE/issues/882

**Comment by nicedevil007** [comment]
Aha :)
Da hab ich jetzt am Ende gar net erst geschaut gehabt, da das mit der Disabletime bei mir halt nur über deine Nodes kam und jedes mal wenn ichs danach über die Originaloberfläche gemacht habe, kam wieder die 15 Min die ich eingabe. Komisch :/

Tja wie kommt die 1 Blocklistennummer da rein.... ungeachtet dessen, wäre es wohl aber generell doch besser, wenn der status deiner Node auf den "status" von Pihole zugreift anstatt die Blocklisteneinträge oder?

Weil man mit nem Switch über Node-red doch den Pihole disabled, möchte man ja entweder den Timer (Bsp.: 15 Min) ablaufen lassen oder vorher von hHand wieder einschalten. Letztere Möglichkeit steht dann aber net zur Verfügung, da der Switch ja wieder eingeschalten ist, da dieser über den status ja enabled bisher erhält. Hoffe konnt das verständlich ausdrücken eieiei :D

**Comment by nicedevil007** [comment]
So habe nun auch mal einen "Rundumschlag" bei Pihole gemacht um den Sachen auf die Schliche zu kommen. Ggf. erweitern die ja auch die API so dass man doch noch Gravity updaten kann und so Zeug :)

Hab dir erstmal wieder vielen Dank. Wenn du magst kannst ja closen oder ggf. antwortet ja wer von Piholeleuten hier?

**Comment by naimo84** [comment]
Hab's gesehn und bin mal gespannt, was da rauskommt ;) Ich lass hier mal offen.

Die Tage hab ich mal ein wenig nach API und pihole gesucht und bin auf ein "neues" Projekt der pi-hole Jungs gestossen. Klingt ganz interessant, wenn das mal released wird. 
https://github.com/pi-hole/api
Aktuell sehe ich noch nicht, wie ich das anprogrammieren kann

**Comment by naimo84** [comment]
Ich mach hier doch mal zu. Ich denke, wenn dann kommentieren die Jungs in ihrem eigenen Thread 😉
