### ISSUE TITLE
Feature Request :)

### ISSUE THREAD

**Issue by nicedevil007** [naimo84/node-red-contrib-pi-hole-remote#5]
Moin moin :)

Offtopic:
Asche über mein Haupt... Node-RED hats bei mir zerstört, durft von vorne anfangen... ja noch kein Backup gehabt :D 

War zwar viel Arbeit alles wieder zu erarbeiten, aber dieses mal aus einem gaaaaaaanz anderen Blickwinkel und ich denke, vieles ist "logischer" geworden.

Feature Request:
Naja nun bin ich über PiHole und deine Node wieder gestolpert und habe festgestellt was noch son bissl Optimierung bedürfen könnte :) 2 Dinge hätte ich:

1. Könntest du den Namen des konfigurierten PiHoles nicht als Name deiner Node durchreichen sobald er konfiguriert ist?

2. Könntest du den Namen des konfigurierte PiHoles mit in das ausgegebene msg.payload object reinknallen?

Besten Dank!

**Comment by naimo84** [comment]
Moin moin :)

zum Offtopic: Das ist mir auch schon mal passiert. Seither nutze ich die Node-red Project Funktion und lade meine Flows damit zu Github (in ein privates Repository hoch) 😉 Damit geht nichts verloren und ich könnte sogar Änderungen rückgängig machen. 

Zum FR:
Meinst du den Namen, den man in meiner Node angeben kann, oder gibt es in piHole auch eine Möglichkeit einen Namen zu vergeben?

Ersteren kann ich natürlich im payload mit ausgeben. Zum letzerem müsste ich noch nachgucken.

**Comment by nicedevil007** [comment]
Hey Ben, danke für die zeitnahe Antwort :)

Ich meine natürlich den Namen, den man in der Config in deiner Node hinterlegt... Wenn du das hinkriegst, denke ich den Flow noch einmal wesentlich kürzer zu kriegen :)

**Comment by naimo84** [comment]
Dein Wunsch sei mir zu Befehl 😁 
zumindest Teil 1 der Requests ^^ siehe version 0.1.0

Den Input msg.pihole schau ich mir noch an 😉

**Comment by nicedevil007** [comment]
Sieht gut aus soweit :)

![image](https://user-images.githubusercontent.com/17103076/71549622-dc050e80-29c0-11ea-97fa-81b6cda90b6e.png)

Hab allerdings auch bissl was mit arrays für context gemacht anstatt die namen fix als variable zu setzen.

**Comment by nicedevil007** [comment]
oh, dein paypal link is broken gell ;)

**Comment by naimo84** [comment]
super, ich hab gestern alerdings etwas zu früh gepusht... Der Name stammte nicht aus der config, sondern direkt aus der Node. Das würde für Teil2 nix bringen, da ich keinen Vergleich habe. Daher gibt's mit v0.1.1 noch eine weitere Eigenschaft: msg.payload.pihole 😉 Das ist der Name der Config

Ob Teil2 funktioniert kann ich Dir aber noch nicht sicher versprechen. Da muss ich mich erst nochmal in die Node-Red Doku einlesen

P.S. Danke für den Hinweis mit PayPal 😃

**Comment by naimo84** [comment]
Hey Manu,
vielen vielen Dank für deine PayPal Überweisung 😉 Freut mich riesig ^^

Mit v0.1.2 kannst du als input payload den pihole namen mitgeben. Dieser sollte dann die richtige Config verwenden.

also msg.payload.pihole = 'pihole 1' z.B.

**Comment by nicedevil007** [comment]
> Hey Manu,
> vielen vielen Dank für deine PayPal Überweisung 😉 Freut mich riesig ^^

Ich hasse selbst die Blutsauger :D Also gern :)

> Mit v0.1.2 kannst du als input payload den pihole namen mitgeben. Dieser sollte dann die richtige Config verwenden.
> 
> also msg.payload.pihole = 'pihole 1' z.B.

Teste es nachher, hab gerade noch mit nem Problem zu kämpfen :/ Vielleicht hast du ne Idee?
Hat aber nix mit PiHole zu tun.

Hab nen msg.payload object das einmal status, effect, color, switch, speed haben kann (ggf. gar auch alle 5) => also msg.payload.status, msg.payload.speed etc...

Wie baut man jetzt ne switch node, die status an ausgang 1 schickt und speed an ausgang 2 usw.?

**Comment by nicedevil007** [comment]
Da ich ja gerade net weiterkomme, wollt ich wenigstens PiHole eben machen.
Es gibt nach wie vor nur 0.1.0 im Angebot im Store :(

![image](https://user-images.githubusercontent.com/17103076/71558763-e376f700-2a56-11ea-804f-26f53ad657a7.png)

**Comment by naimo84** [comment]
Sorry, dass ich jetzt erst schreibe. Meine Tochter ist heute etwas anstrengender als sonst 😉👶

Wie ich sehe, wurde deine Frage aber ohnehin schon beantwortet. Freut mich. 

v0.1.2 ist bei mir schon verfügbar. Den Update Mechanismus von node red hab ich auch noch nicht ganz durchblickt.

**Comment by nicedevil007** [comment]
mhhh immer noch net :/ kp ob das hält wenn ichs manuell installiere, nutze docker ;)

**Comment by nicedevil007** [comment]
Ok, das passiert wenn ich das so da reinschmeiße

![image](https://user-images.githubusercontent.com/17103076/71562992-091cf400-2a89-11ea-899a-447ce1d8e4a3.png)

**Comment by nicedevil007** [comment]
Hey Ben, danke für das Update :)
Läuft aber noch net ganz... bin schon fleißig am testen.

![image](https://user-images.githubusercontent.com/17103076/71575069-cb9d8280-2aeb-11ea-8542-e83a7f4ccaf3.png)

Schau mal da, die erste nachricht ist mit 'PiHole #1' und die zweite mit 'PiHole #2'.
Den Namen scheint er zu überschreiben aus irgend einem Grund, so dass der Output jeweils 2x PiHole #2 ist. Ich lasse das gerade im 5 sec Abstand zueinander in deine Node fließen.

Du siehst, dass es 2 verschiedene PiHole sind an der Zahl der blocked Domains :)

Uuuuuuuuund noch kleine Kosmetik => payload.name kannst jetzt rausschmeißen ;)

**Comment by nicedevil007** [comment]
Ok, vergiss es :D das hat nur was mit überflutung von msg in deiner node zu tun ;)

Kann ja net 2 payloads reinschmeißen und die dann so schnell abarbeiten.

Bleibt nur das payload.name :D

**Comment by naimo84** [comment]
Hey Manu,
Sorry dass ich momentan etwas wortkarg bin 😉 das payload.name würd ich evtl sogar drin lassen. Evtl kann jemand anderes es ja noch brauchen 😉 allerdings nur anzeigen, wenn kein leer string.

**Comment by nicedevil007** [comment]
jo das klingt auch gut :)
