### ISSUE TITLE
Feature Request #2

### ISSUE THREAD

**Issue by nicedevil007** [naimo84/node-red-contrib-pi-hole-remote#7]
Denkste es ist möglich, dass deine Node automatisch die Anzahl der reingeschmissenen messages erkennt und erst eine abarbeitet und die nächste erst startet sobald eine message aus deiner node ausgegeben wurde? Das wäre godlike, spiele aktuell mit ner statustime von 5000 ms und lasse über nen loop die 2. message nach 5250 ms reinschmeißen. Wenn er es automatisch erkennt wäre das natürlich geil.

Andere alternative wäre z.B. eine msg mit folgendem inhalt reinknallen:

msg.payload: {statustime: 5, disabletime: 900, pihole: all} 

Deine Node erkannt, wenn all auf msg.payload.pihole eingeht, dass er ALLE configurierten piholes den befehl übermittelt und mit nem delay von z.B. 10 ms die status messages rausknallt oder gar "sammelt" und dann in einer msg rauswirft also am besten in einem array, so könnte man die abfrage mit ner for schleife in einer function node danach machen :D 

Unnnd falls das too much wird und man einfach es jetzt so lassen sollte wie es ist, ist das auch iO. Bin son kleiner Perfektionist... werde immer was finden was man optimieren verbessern etc. könnte, aber irgendwann is natürlich auch genug gell ;)

**Comment by naimo84** [comment]
A gutes neues 😉 
Ich denke, beides müsste möglich sein.
Variante 2 gefällt mir persönlich aber fast besser. Und dürfte auch deutlich einfacher umzusetzen sein 😀

Bei Variante 1 sehe ich gerade noch keinen Unterschied zu der bisherigen Lösung. Node-red sollte das eig. genauso regeln.

**Comment by nicedevil007** [comment]
Variante 1 funzt definitiv net ;)

Ich schmeiß 2 verschiedene msg mit nem delay von z.b. 250 ms rein und deine Node kommt dann leider net hinterher und verwechselt den namen vom pihole teilweise (siehe auch das bereits geclosete issue).

Aber wenn Variante 2 klappt, dann is das alles eh obsolet :D Könntest da ja sogar nen Haken in die confignode reinmachen, so dass man anklicken kann "immer Alle abfragen" oder sowas :)

**Comment by naimo84** [comment]
Mit v0.1.4 sollte nun beide Varianten funktionieren 😉 

Variante 1 hätte theoretisch vorher schon funktioniert... wenn ich's richtig programmiert hätte 😉
